# Generated by Django 5.0 on 2023-12-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('history_id', models.IntegerField()),
                ('user_message', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='is_file_exist',
            field=models.BooleanField(default=False),
        ),
    ]
