# Generated by Django 4.2.5 on 2023-12-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
